"""NDJSON CLI that reuses the shared parser and conversion logic."""

import argparse
import logging
import os
import sys
from typing import Dict

from .. import conv_to_eml
from .common import make_out_filename
from ..parsers import imessage_json


def main(argv=None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    parser = argparse.ArgumentParser(description='Convert imessage-exporter NDJSON to .eml files')
    parser.add_argument('infile', help='Input NDJSON file')
    parser.add_argument('outdir', nargs='?', default=os.getcwd(), help='Output directory (defaults to cwd)')
    parser.add_argument('--local-handle', help='Local account handle (phone/email) to use for From:', default=None)
    parser.add_argument('--idle-hours', type=float, default=8.0, help='Idle gap hours to segment conversations')
    parser.add_argument('--min-messages', type=int, default=2, help='Minimum messages to keep a segment')
    parser.add_argument('--max-messages', type=int, default=0, help='Force split at this many messages (0=unlimited)')
    parser.add_argument('--max-days', type=int, default=0, help='Force split if segment spans more than N days (0=unlimited)')
    parser.add_argument('--stream', action='store_true', help='Shard input to disk to avoid large memory use (auto-enabled for large files)')
    parser.add_argument('--stream-tempdir', default=None, help='Directory to store per-chat shards (default: autogenerated tempdir)')
    parser.set_defaults(embed_attachments=True)
    parser.add_argument('--embed-attachments', dest='embed_attachments', action='store_true', help=argparse.SUPPRESS)
    parser.add_argument('--no-attach', dest='embed_attachments', action='store_false', help='Do not embed attachment payloads in EML; keep path metadata only')
    parser.add_argument('--no-background', action='store_true', help='Strip background style from HTML')
    parser.set_defaults(clobber=True)
    parser.add_argument('--clobber', action='store_true', help='Overwrite existing .eml files')
    parser.add_argument('--debug', action='store_true', help='Enable debug logging')
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.DEBUG if args.debug else logging.INFO)

    infile = args.infile
    outdir = args.outdir
    if not os.path.isfile(infile):
        logging.critical('Input file not found: %s', infile)
        return 1
    if not os.path.isdir(outdir):
        os.makedirs(outdir, exist_ok=True)

    stream = args.stream
    try:
        fsize = os.path.getsize(infile)
    except Exception:
        fsize = 0
    # If input file is larger than this threshold, auto-enable streaming to
    # shard per-chat data to disk to bound memory usage. Threshold is in bytes.
    AUTOSTREAM_THRESHOLD = 50 * 1024 * 1024
    if not stream and fsize > AUTOSTREAM_THRESHOLD:
        stream = True
        logging.info('Input file large (%d bytes) - enabling streaming shards', fsize)

    idx_counters: Dict[str, int] = {}
    # Wrap the top-level conversion loop so a single unexpected error results
    # in a non-zero exit; this mirrors the error-handling behavior used by the
    # Apple DB CLI and makes batch runs more robust.
    try:
        for conv in imessage_json.parse_file(
            infile,
            local_handle=args.local_handle,
            idle_hours=args.idle_hours,
            min_messages=args.min_messages,
            max_messages=args.max_messages,
            max_days=args.max_days,
            stream=stream,
            stream_dir=args.stream_tempdir,
            embed_attachments=args.embed_attachments,
        ):
            chat_id = conv.filenameuserid or conv.origfilename or 'chat'
            startdate = conv.startdate
            if not startdate:
                try:
                    startdate = conv.getoldestmessage().date
                except Exception:
                    startdate = None
            idx = idx_counters.get(chat_id, 0)
            outname = make_out_filename(chat_id, startdate or '', idx)
            outpath = os.path.join(outdir, outname)
            if os.path.exists(outpath) and not args.clobber:
                logging.warning('Skipping existing file %s (use --clobber to overwrite)', outpath)
                idx_counters[chat_id] = idx + 1
                continue
            try:
                eml = conv_to_eml.mimefromconv(conv, args.no_background)
            except Exception as e:
                logging.error('Failed to create MIME for chat %s: %s', chat_id, e)
                idx_counters[chat_id] = idx + 1
                continue

            if conv.filenameuserid:
                eml['X-Chat-Identifier'] = conv.filenameuserid
            _chat_guid = getattr(conv, 'chat_guid', None)
            if _chat_guid:
                eml['X-Chat-GUID'] = _chat_guid
            if hasattr(conv, 'startdate') and conv.startdate:
                eml['X-Segment-Start'] = conv.startdate.isoformat()
            if conv.messages:
                eml['X-Segment-Messages'] = str(len(conv.messages))
            imsvc = getattr(conv, 'service', None)
            if imsvc:
                eml['X-iMessage-Service'] = imsvc
            eml['X-Converted-By'] = os.path.basename(sys.argv[0])

            try:
                with open(outpath, 'w') as fo:
                    fo.write(eml.as_string())
                logging.info('Wrote %s', outpath)
            except Exception as e:
                logging.error('Failed to write %s: %s', outpath, e)
            idx_counters[chat_id] = idx + 1
    except Exception as e:
        logging.error('Conversion failed: %s', e)
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
